{
 "title": "Dashboard-Sistema_Bancario",
 "description": "Dashboard que monitora a API de uma aplicação web de um sistema bancário fictício",
 "tags": [
  "API",
  "LLD",
  "Saldo"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Group", "label": "Selecione um grupo de host.", "query": "*" },
   {
    "name": "Host",
    "label": "Selecione um host pertencente ao grupo.",
    "query": "$Group.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Taxa de download da API da aplicação",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "API" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Download speed for scenario \"Monitorando a API da aplicação\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo de resposta da aplicação",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "application": { "filter": "API" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Response time for step \"Acessando a API Swagger\" of scenario \"Monitorando a API da aplicação\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "API" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Failed step of scenario \"Monitorando a API da aplicação\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Alertas no Zabbix",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": {
    "0": { "refId": "A" },
    "Zabbix": {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "title": "Saldo da conta - 53",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "currencyBRL" }
   ],
   "targets": [
    {
     "application": { "filter": "Saldo" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "LLD: Saldo da conta 53" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Saldo da conta - 52",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "currencyBRL" }
   ],
   "targets": [
    {
     "application": { "filter": "Saldo" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "LLD: Saldo da conta 52" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}